DELIMITER //
CREATE FUNCTION LOGIN(USERNAME_IN VARCHAR(255), PASSWORD_IN VARCHAR(255))
RETURNS INTEGER  DETERMINISTIC
BEGIN
	RETURN IF ((SELECT COUNT(ID_USER_SYSTEM) FROM USER_SYSTEM WHERE
		USERNAME = USERNAME_IN AND PASSWORD = MD5(PASSWORD_IN)) <> 0, 1, 0);
END
//

DELIMITER //
CREATE FUNCTION GET_ID_USER_BY_USERNAME( USERNAME_IN VARCHAR( 255 ) )
RETURNS INTEGER DETERMINISTIC
BEGIN
	RETURN ( SELECT ID_USER_SYSTEM FROM USER_SYSTEM WHERE USERNAME = USERNAME_IN );
END //

DELIMITER //
CREATE OR REPLACE FUNCTION CREATE_USER(USERNAME_IN  VARCHAR(255),
		PASSWORD_IN VARCHAR(255),
		EMAIL_IN VARCHAR(255),
		PROFILE_IN INTEGER)     
RETURNS INTEGER DETERMINISTIC
BEGIN
	INSERT INTO USER_SYSTEM (USERNAME, PASSWORD, EMAIL, PROFILE)
	VALUES (USERNAME_IN, MD5(PASSWORD_IN), EMAIL_IN, PROFILE_IN);
	RETURN 1;
END //

DELIMITER //
CREATE PROCEDURE GET_PETS_BY_OWNER( OWNER_IN INTEGER )
BEGIN
	SELECT * FROM `animal` WHERE `OWNER` = OWNER_IN;
END //